### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by crosenth** [nhoffman/alnvu#10]
`av --consensus --reference-top --simchar . --trim-to "1" input.afa`
```Traceback (most recent call last):
  File "av", line 11, in <module>
    load_entry_point('alnvu==0.3.3', 'console_scripts', 'av')()
  File "lib/python3.6/site-packages/alnvu/av.py", line 263, in main
    reference_top=args.reference_top)
  File "lib/python3.6/site-packages/alnvu/util.py", line 153, in reformat
    start, stop = get_extent(get_seq_from_list(trim_to, seqlist).seq)
  File "lib/python3.6/site-packages/alnvu/util.py", line 69, in get_extent
    start = re.search(r'[a-z]', seqstr, flags=re.I).start()
AttributeError: 'NoneType' object has no attribute 'start'
```

[input.txt](https://github.com/nhoffman/alnvu/files/5675010/input.txt)

**Comment by crosenth** [comment]
PR https://github.com/nhoffman/alnvu/pull/11
