### ISSUE TITLE
error when using --rename-from-file in python 3

### ISSUE THREAD

**Issue by tholland** [nhoffman/alnvu#7]
In python 3 the following error occurs when using --rename-from-file:
```
Traceback (most recent call last):
  File "/mnt/disk2/molmicro/working/timholl/sanger_singularity/sanger_singularity-env/bin/av", line 11, in <module>
    sys.exit(main())
  File "/mnt/disk2/molmicro/working/timholl/sanger_singularity/sanger_singularity-env/lib/python3.6/site-packages/alnvu/av.py", line 237, in main
    seq.name = namedict.get(seq.name, seq.name)
AttributeError: can't set attribute
```
Tuples are now immutable in py3, so setting the name this way doesn't work.  An alternative mutable tuple library exists that could be used as a quick substitute: https://pypi.python.org/pypi/recordclass

**Comment by nhoffman** [comment]
Thanks, @tholland - fixed in version 0.3.2
